### ISSUE TITLE
Suggestion: offer palette in TID or JSON format

### ISSUE THREAD

**Issue by mateuszwilczek** [SlyBouhafs/TiddlyWikiDracula#3]
The palette is currently only available as raw dictionary data, which requires multiple steps to add it to TiddlyWiki.

I suggest that it is made available as a downloadable file in TID or JSON format. This would make adding it to TiddlyWiki much simpler (download file, drag-and-drop on TW, click Import). TID would be much easier to maintain and read. The TID file would just need to have these lines, including the single empty line, before the contents of the /sample/Dracula file:

```
author: SlyBouhafs, Zeno Rocha
color-scheme: dark
description: Dark palette for TiddlyWiki
license: MIT, https://github.com/dracula/tiddlywiki/blob/master/LICENSE
name: Dracula
tags: $:/tags/Palette
title: $:/palettes/Dracula
type: application/x-tiddler-dictionary

```

**Comment by SlyBouhafs** [comment]
@mateuszwilczek Hey! Thanks for opening an issue.

Yeah, sure!
